#cloud-config
ssh_pwauth: false
users:
  - name: nutanix
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDIc4TD2hzbvpO1WhQ6W36eP+3Ixnzq9UO764dm7H+7skBXGSYuUSgsZwzVQ40/III/yGsuN+/XZ0ZDgacaxBTThKMqpqm5nlJjrR5r/OEAE1bIaMJ6BGvZaWu+EYifnCyTcauuAFXiHn4KFHzkpLPGry27nbHJ/hffS8zf6P+uVZZwXsatTfUyh6uvDXVIY1An6VEHS16KxiVcGe5lRk2tXv3Hnn1S75zsmc3vdNTISqN8kZRK/EF3bMSm+cdpSort1JmR0Kca81T69MCJMYY2C+RG67MlJTrsJgNDBkA2N4sB9kqneZGuhoH5P2gqauvm+sjTIoYNBHLT9hRRa8WYlxhOCpFO5fz29wmiOQGgo6URaE1xig3UiBWwaF3hlNpq6lYlMYkAkRfoggrd267Q9Qmmia6+fqNE8rg+wnINugUSCtQao+Bsr+77FynBfzEMkskJ4X/V7rZWaBVlgvoxAxrkFHmnY2CIB7RrrYzUDrvJMXQR484NoCCGdPO+9f8="
bootcmd:
- mkdir -p /etc/docker
write_files:
- content: |
    {
        "insecure-registries": ["registry.nutanixdemo.com"]
    }
  path: /etc/docker/daemon.json
runcmd:
- '[ ! -f "/etc/yum.repos.d/nutanix_rocky9.repo" ] || mv -f /etc/yum.repos.d/nutanix_rocky9.repo /etc/yum.repos.d/nutanix_rocky9.repo.disabled'
- dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
- dnf -y install docker-ce docker-ce-cli containerd.io
- systemctl --now enable docker
- usermod -aG docker nutanix
- 'curl -Lo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl'
- chmod +x /usr/local/bin/kubectl
- 'curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash'
- eject
- 'wall "If you are seeing this message, please reconnect your SSH session. Otherwise, the NKP CLI installation process may fail."'
final_message: "The machine is ready after $UPTIME seconds. Go ahead and install the NKP CLI using: $ curl -sL https://raw.githubusercontent.com/nutanixdev/nkp-quickstart/main/scripts/get-nkp-cli | bash"